# Generated by Django 4.2.10 on 2024-08-18 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
    ]
