# Generated by Django 4.2.10 on 2024-08-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
